language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pefile
  - pip install codecov
  - pip install coveralls
  - pip install pytest pytest-cov

script:
  - python setup.py install
  - pytest --cov=pefiles_scripts

after_success:
  - codecov
  - coveralls